config/routes.rb
Rails.application.routes.draw do

  post '/tickets' => 'tickets#create',   as: "create_ticket"
  get "/tickets"  => "tickets#index",     as: "tickets"
  delete "/ticket" => "tickets#destroy", as: "ticket"

  post "/ticket" => "tickets#update",   as: "update_ticket"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/orders/:server_id' => 'orders#create', as: "create_order"
  get "/orders"  => "orders#index", as: "orders"
  get "/orders/:id" => "orders#show", as: "get_order"
  patch "/orders/:id" => "orders#update", as: "edit_order"
  delete "/orders" => "orders#destroy", as: "order"

  resources :items, only: [:index, :show, :new, :create]
  resources :charges
  
  get "/dashboard" => "servers#show"

  namespace :admin do
    get "/dashboard" => "dashboard#show"

    resources :servers, only: [:edit, :update]
    resources :items
  end

  resources :servers, except: [:show]

  get "/menu"  => "categories#index", as: "menu"
  root "categories#index"

  get "/:category_name" => "categories#show", as: "category_name"
end

app/models/Dashboard.rb
class Dashboard
  attr_reader :servers, :orders, :items, :order, :admin, :status_order, :status, :roles, :unique_statuses

  def initialize
    @servers  = Server.all
    @orders   = Order.all
    @items    = Item.all
    @order    = Order.new
    @status_order = set_status_order
    @roles = Server.select("DISTINCT role")
    @unique_statuses = Order.select("DISTINCT status")
  end

  def set_admin(server_id)
    @admin = Server.find(server_id)
  end

  def set_status(order_status)
    @status = order_status
  end

  def set_status_order
    if @status.nil? || @status == ''
      @status_order = orders
    else
      @status_order = Order.where(status: @status)
    end
  end
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :require_admin

  def show
    @dashboard = Dashboard.new
    @dashboard.set_admin(session[:server_id])
    @dashboard.set_status(params[:order][:status]) if params[:order]
    @dashboard.set_status_order
  end

private

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/views/admin/dashboard/_item_list.html.erb
<div class='col-md-4 col-md-offset-1 jumbotron'>
  <h3 class="header">Items</h3>
  <table class="admin-tables admin-tables-overflow table-responsive">
    <tr><th>Name</th><th>Price</th><th>Category</th></tr>
    <% @dashboard.items.each do |item|%>
    <tr class="item_<%= item.id %>">
        <td><%= link_to item.name, edit_admin_item_path(item) %></td>
        <td><%= number_to_currency(item.price, :unit => "$") %></td>
        <td><%= item.category.name %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/dashboard/_order_list.html.erb
<table>
  <thead>
    <tr><th>ID</th><th>Server</th><th>Status</th><th></th><th></th></tr>
  </thead>
  <% @dashboard.status_order.each do |order| %>
    <tr id="order_<%=order.id%>">
      <td><%= link_to order.id, get_order_path(order) %></td>
      <td><%= order.server.name %></td>
      <td><%= order.status %></td>
      <% if order.status == "paid" %>
        <td><%= button_to "Cancel", edit_order_path(order, status: :cancelled), method: "patch", class:"btn btn-danger btn-small" %></td>
        <td><%= button_to "Completed ", edit_order_path(order, status: :completed), method: "patch", class:"btn btn-danger btn-small" %></td>
      <% elsif order.status == "ordered" %>
        <td><%= button_to "Cancel", edit_order_path(order, status: :cancelled), method: "patch", class:"btn btn-danger btn-small" %></td>
        <td><%= button_to "Paid", edit_order_path(order, status: :paid), method: "patch", class:"btn btn-danger btn-small" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/dashboard/_server_list.html.erb
<div class='col-md-4 col-md-offset-1 jumbotron'>
  <h3 class='header'>Servers</h3>
  <table class="admin-tables admin-tables-height">
    <thead>
      <tr><th>Server</th><th>Role</th></tr>
    </thead>
    <tbody>
      <% @dashboard.servers.each do |server|%>
      <tr id="server_<%= server.id %>">
          <td><%= server.name %></td>
          <td>
            <%= form_for server, url: admin_server_path(server) do |f| %>
              <%= f.collection_select :role, @dashboard.roles, :role, :role, {:id=>'server-dropdown'}  %>
          </td>
          <td>
            <%= f.submit "Update", class: "btn btn-info" %>
          </td>
          <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard/_status_count.html.erb
<div class='col-md-4 col-md-offset-1 jumbotron'>
  <h3 class="header">Orders</h3>
  <table class="table-orders table-order-count table-responsive">
    <tr>
      <% @dashboard.order.statuses.each do |status| %>
      <th> <%= status.capitalize %></th>
      <% end %>
    </tr>
    <tr>
      <% @dashboard.order.status_count.each do |status_id, count| %>
      <td> <%= count %> </td>
      <% end %>
    </tr>
  </table>
</div>

app/views/admin/dashboard/_status_list.html.erb
<div class='col-md-4 col-md-offset-1 jumbotron table-responsive'>
  <div class="order_partial admin-table-orders admin-div-overflow">
    <%= form_tag(admin_dashboard_path, method: "get") do %>
    <%= collection_select :order, :status, @dashboard.unique_statuses, :status, :status, {include_blank: "all"}  %></br>
    <%= submit_tag "Submit", class: "btn btn-info btn-padding" %>
    <% end %>
    <%= render partial: "order_list" %>
  </div>
</div>

app/views/admin/dashboard/show.html.erb
<h1>Admin Dashboard</h1>

<h3>Name: <%= current_user.name %></h3></br>
<%= link_to "Edit Admin Account", edit_admin_server_path(@dashboard.admin), class:"btn btn-default btn-padding" %>
<%= link_to "New Item", new_admin_item_path, class:"btn btn-default btn-padding" %>
<%= link_to "All Items", admin_items_path, class:"btn btn-default btn-padding" %>

<div class="container-fluid">
  <div class="row">
    
    <%= render partial: "server_list" %>

    <%= render partial: "item_list" %>

    <%= render partial: "status_list" %>

    <%= render partial: "status_count" %>

  </div>
</div>