config/routes.rb
Rails.application.routes.draw do

  post '/tickets' => 'tickets#create',   as: "create_ticket"
  get "/tickets"  => "tickets#index",     as: "tickets"
  delete "/ticket" => "tickets#destroy", as: "ticket"

  post "/ticket" => "tickets#update",   as: "update_ticket"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/orders/:server_id' => 'orders#create', as: "create_order"
  get "/orders"  => "orders#index", as: "orders"
  get "/orders/:id" => "orders#show", as: "get_order"
  patch "/orders/:id" => "orders#update", as: "edit_order"
  delete "/orders" => "orders#destroy", as: "order"

  resources :items, only: [:index, :show, :new, :create]
  resources :charges
  
  get "/dashboard" => "servers#show"

  namespace :admin do
    get "/dashboard" => "dashboard#show"

    resources :servers, only: [:edit, :update]
    resources :items
  end

  resources :servers, except: [:show]

  get "/menu"  => "categories#index", as: "menu"
  root "categories#index"

  get "/:category_name" => "categories#show", as: "category_name"
end

app/models/Dashboard.rb
class Dashboard
  attr_reader :servers, :orders, :items, :order, :admin, :status_order, :status, :roles, :unique_statuses

  def initialize
    @servers  = Server.all
    @orders   = Order.all
    @items    = Item.all
    @order    = Order.new
    @status_order = set_status_order
    @roles = Server.select("DISTINCT role")
    @unique_statuses = Order.select("DISTINCT status")
  end

  def set_admin(server_id)
    @admin = Server.find(server_id)
  end

  def set_status(order_status)
    @status = order_status
  end

  def set_status_order
    if @status.nil? || @status == ''
      @status_order = orders
    else
      @status_order = Order.where(status: @status)
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true


  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base  
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true

  belongs_to :category, optional: true, dependent: :destroy
  has_many :ticket_items
  has_many :tickets, through: :ticket_items
  
  has_attached_file :avatar, styles: {
   thumb: '100x100>',
   square: '200x200>',
   medium: '300x300>'
  }

 # Validate the attached image is image/jpg, image/png, etc
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/order.rb
class Order < ApplicationRecord
  validates :total, presence: true
  validates :server_id, presence: true


  belongs_to :server, optional: true, dependent: :destroy
  has_many :order_items
  has_many :items, through: :order_items
  enum status: [:ordered, :paid, :cancelled, :completed]

  def prep_for_show
    grouped_items = items.group_by {|item| item.id}
    a = grouped_items.reduce([]) do |array, (quantity, item) |
      array << [item.first, item.count, (item.first.price * item.count)]
      array
    end
  end

  def completed_or_cancelled?
    true ? self.status == "completed" || self.status == "cancelled" : false
  end

  def statuses
    [:ordered, :paid, :cancelled, :completed]
  end

  def status_count
    Order.group(:status).count
  end
  
  def total_in_cents
    @total_in_cents = (self.total * 100).round
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order_items.rb
class OrderItems < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/server.rb
class Server < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :tables

  enum role: [:default, :admin]
  has_many :orders



end

app/models/table.rb
class Table < ActiveRecord::Base
  validates :location, presence: true, uniqueness: true

  belongs_to :server, optional: true
  has_many :table_items
  has_many :items, through: :table_items
end

app/models/table_item.rb
class TicketItem < ApplicationRecord
  belongs_to :ticket
  belongs_to :item
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  attr_reader :contents

  has_many :ticket_items
  has_many :items, through: :ticket_items
  belongs_to :server

  def initialize(initial_contents = nil)
    @contents = initial_contents || Hash.new
  end

  def add_item(item_id)
    @contents[item_id.to_s] ||= 0
    @contents[item_id.to_s] += 1
  end

  def items
    @contents.reduce({}) do |hash, (id, quantity)|
      hash[Item.find(id.to_i)] = quantity
      hash
    end
  end

  def delete(item_id)
    @contents.delete(item_id.to_s)
  end

  def update_quantity(item_id, quantity)
    @contents[item_id.to_s] = quantity.to_i
    delete(item_id.to_s) if quantity.to_s == "0"
  end

  def total
    items.reduce(0) {|sum, (item,quantity)| sum += item.price*quantity.to_f}
  end

  def create_order_items(order_id)
    items.each {|item,quantity| quantity.to_i.times {OrderItem.create(item_id:item.id, order_id:order_id)}}
  end

end

app/models/ticket_item.rb
class TicketItem < ApplicationRecord
  belongs_to :ticket
  belongs_to :item
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    raw_total = session[:current_order_total]
    @amount = (raw_total * 100).to_i
    @total_display = raw_total

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Mobile checkout customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end
  
private

  def item_params
    params.require(:item).permit(:name, :avatar, :price)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_log_in

  def index
    @server = Server.find(session[:server_id])
    @orders = @server.orders.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    server = Server.find(server_id)
    order = Order.new(server_id: server.id, total: @ticket.total )
    session[:current_order_total] = order.total
    session.delete :ticket
    if order.save
      create_order_items(order.id)
      redirect_to orders_path
    else
      redirect_to dashboard_path
    end
  end

  def update
    order = Order.find(params[:id])
    order.update_attributes(status: cancelled) if cancelled
    order.update_attributes(status: completed) if completed
    order.update_attributes(status: paid)      if paid
    redirect_to admin_dashboard_path
  end


  private

  def server_id
    params.permit(:server_id)[:server_id].to_i
  end

  def create_order_items(order_id)
    @ticket.create_order_items(order_id)
  end

  def require_log_in
    render file: '/public/404' unless logged_in?
  end

  def cancelled
    return "cancelled" if params[:status] == "cancelled"
  end

  def completed
    return "completed" if params[:status] == "completed"
  end

  def paid
    return "paid" if params[:status] == "paid"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Check Please!</title>

    <%= stylesheet_link_tag    'application_css', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    
    <%= render partial: "shared/navbar" %>
    
    <% flash.each do |type, message| %>
      <div class="center-content center-block container alert alert-<%= type %>"><%= message %>
    <% end  %>
      </div>
    <div class="container center-content">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Check Please!</title>

    <%= stylesheet_link_tag    'application_css', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    
    <%= render partial: "shared/navbar" %>
    
    <% flash.each do |type, message| %>
      <div class="center-content center-block container alert alert-<%= type %>"><%= message %>
    <% end  %>
      </div>
    <div class="container center-content">
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
<div>
  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#login-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand-logo navbar-brand" href="/">CHECK PLEASE</a>
      </div>
      
      <ul class="col-md-4 nav form-inline navbar-nav navbar-left">
        <li>
          <form>
              <%= form_tag items_path, method: 'get', class: 'form-inline', role: 'search' do %>
                <div class="input-group form-inline navbar-form">
                  <%= text_field_tag :query, params[:query], size: 20, placeholder: "Search", class: "form-control"%>
                </div>
              <%= submit_tag 'Search', class: 'btn btn-success' %>
            <% end %>
          </form>
        </li>
      </ul>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="login-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          
          <% if logged_in? %>
            <li><p class="logged-in-text-style">Logged in as <%= link_to current_user.username, dashboard_path %> | <%= link_to "Logout", logout_path, method: :delete %> </p></li>
            <%= link_to "Orders", orders_path, class: "admin-dashboard-button btn btn-default" %>
          <% else %>
            <a type="button" href="/login" class="btn btn-default navbar-btn login-button-margin">Login</a>
          <% end %>

          <% if current_admin? %>
            <%= link_to "Admin Dashboard", admin_dashboard_path, class: "admin-dashboard-button btn btn-default" %>
          <% end %>
          
        </ul>
      </div><!-- /.navbar-collapse -->

    </div><!-- /.container-fluid -->
  </nav>
</div>
<br/>
<br/>
<div>
  <nav class="navbar navbar-default navbar-fixed-top menu-nav">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="menu-navbar-collapse-2">
        <ul class="nav navbar-nav menu-nav-selectors">
          <% @categories.each do |category| %>
          <li class="menu-nav-selectors"> <%= link_to category.name, category_name_path(category.name.parameterize) %> </li>
          <% end %>
          <%= link_to tickets_path, id: "ticket" do %>
            <button type="button" class="btn btn-success glyphicon glyphicon-shopping-cart glyphicon-button-fix"><span class="ticket-button-font" id="navbar-ticket">Ticket</span></button>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->

    </div><!-- /.container-fluid -->
  </nav>

</div>