config/routes.rb
Rails.application.routes.draw do

  post '/tickets' => 'tickets#create',   as: "create_ticket"
  get "/tickets"  => "tickets#index",     as: "tickets"
  delete "/ticket" => "tickets#destroy", as: "ticket"

  post "/ticket" => "tickets#update",   as: "update_ticket"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/orders/:server_id' => 'orders#create', as: "create_order"
  get "/orders"  => "orders#index", as: "orders"
  get "/orders/:id" => "orders#show", as: "get_order"
  patch "/orders/:id" => "orders#update", as: "edit_order"
  delete "/orders" => "orders#destroy", as: "order"

  resources :items, only: [:index, :show, :new, :create]
  resources :charges
  
  get "/dashboard" => "servers#show"

  namespace :admin do
    get "/dashboard" => "dashboard#show"

    resources :servers, only: [:edit, :update]
    resources :items
  end

  resources :servers, except: [:show]

  get "/menu"  => "categories#index", as: "menu"
  root "categories#index"

  get "/:category_name" => "categories#show", as: "category_name"
end

app/models/order.rb
class Order < ApplicationRecord
  validates :total, presence: true
  validates :server_id, presence: true


  belongs_to :server, optional: true, dependent: :destroy
  has_many :order_items
  has_many :items, through: :order_items
  enum status: [:ordered, :paid, :cancelled, :completed]

  def prep_for_show
    grouped_items = items.group_by {|item| item.id}
    a = grouped_items.reduce([]) do |array, (quantity, item) |
      array << [item.first, item.count, (item.first.price * item.count)]
      array
    end
  end

  def completed_or_cancelled?
    true ? self.status == "completed" || self.status == "cancelled" : false
  end

  def statuses
    [:ordered, :paid, :cancelled, :completed]
  end

  def status_count
    Order.group(:status).count
  end
  
  def total_in_cents
    @total_in_cents = (self.total * 100).round
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_log_in

  def index
    @server = Server.find(session[:server_id])
    @orders = @server.orders.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    server = Server.find(server_id)
    order = Order.new(server_id: server.id, total: @ticket.total )
    session[:current_order_total] = order.total
    session.delete :ticket
    if order.save
      create_order_items(order.id)
      redirect_to orders_path
    else
      redirect_to dashboard_path
    end
  end

  def update
    order = Order.find(params[:id])
    order.update_attributes(status: cancelled) if cancelled
    order.update_attributes(status: completed) if completed
    order.update_attributes(status: paid)      if paid
    redirect_to admin_dashboard_path
  end


  private

  def server_id
    params.permit(:server_id)[:server_id].to_i
  end

  def create_order_items(order_id)
    @ticket.create_order_items(order_id)
  end

  def require_log_in
    render file: '/public/404' unless logged_in?
  end

  def cancelled
    return "cancelled" if params[:status] == "cancelled"
  end

  def completed
    return "completed" if params[:status] == "completed"
  end

  def paid
    return "paid" if params[:status] == "paid"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_payment_button.html.erb
<form action="/charges" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_3xzTluUGyKhLta6zmufkcCdd"
    data-amount="<%= @order.total_in_cents %>"
    data-name="Thanks for visiting!"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-zip-code="true">
  </script>
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
</form>

app/views/orders/index.html.erb
<h1>All Orders</h1>

<div class="orders-width center-block jumbotron">
  <table class="table-font table table-hover table-condensed">
    <tr><th class="center-content">Order</th><th class="center-content">Status</th></tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to "Order #{order.id}", get_order_path(order.id) %></td>
        <td><%= order.status %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/orders/show.html.erb
<h3><%= link_to "Order #{@order.id}", order_path(@order) %> : <%= @order.status.capitalize %></h3>
<h5> Ordered by: <%= @order.server.name %></h5>
<h5> Username: <%= @order.server.username %> </h5>

<% if @order.completed_or_cancelled? == false %>
  <%= render partial: "payment_button" %>
<% end %>

<div class="orders-width center-block jumbotron">
  <table class="table-font table table-hover table-orders">
    <thead>
      <tr><th>Item</th><th>Price</th><th>Quantity</th><th>Subtotal</th></tr>
    </thead>
    <tbody>
      <% @order.prep_for_show.each do |(item, quantity, subtotal)| %>
      <tr>
        <td><%= link_to item.name, item_path(item.id) %></td>
        <td><%= number_to_currency(item.price, :unit =>"$")%></td>
        <td><%= quantity %></td>
        <td><%= number_to_currency(subtotal, :unit => "$") %></td>
      </tr>
      <% end %>
      <tr>
        <td></td><td></td>
        <td>Total</td>
        <td><%= number_to_currency(@order.total, :unit => "$") %></td>
      </tr>
    </tbody>
  </table>
  
  <p>
    <p>Order created at: <%= @order.created_at %></p>
  </p>
  
  <p>
    <% if @order.completed_or_cancelled? %>
    <p>Order <%= @order.status %> at <%= @order.updated_at %></p>
    <% end %>
  </p>

</div>