config/routes.rb
Rails.application.routes.draw do

  post '/tickets' => 'tickets#create',   as: "create_ticket"
  get "/tickets"  => "tickets#index",     as: "tickets"
  delete "/ticket" => "tickets#destroy", as: "ticket"

  post "/ticket" => "tickets#update",   as: "update_ticket"

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/orders/:server_id' => 'orders#create', as: "create_order"
  get "/orders"  => "orders#index", as: "orders"
  get "/orders/:id" => "orders#show", as: "get_order"
  patch "/orders/:id" => "orders#update", as: "edit_order"
  delete "/orders" => "orders#destroy", as: "order"

  resources :items, only: [:index, :show, :new, :create]
  resources :charges
  
  get "/dashboard" => "servers#show"

  namespace :admin do
    get "/dashboard" => "dashboard#show"

    resources :servers, only: [:edit, :update]
    resources :items
  end

  resources :servers, except: [:show]

  get "/menu"  => "categories#index", as: "menu"
  root "categories#index"

  get "/:category_name" => "categories#show", as: "category_name"
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  attr_reader :contents

  has_many :ticket_items
  has_many :items, through: :ticket_items
  belongs_to :server

  def initialize(initial_contents = nil)
    @contents = initial_contents || Hash.new
  end

  def add_item(item_id)
    @contents[item_id.to_s] ||= 0
    @contents[item_id.to_s] += 1
  end

  def items
    @contents.reduce({}) do |hash, (id, quantity)|
      hash[Item.find(id.to_i)] = quantity
      hash
    end
  end

  def delete(item_id)
    @contents.delete(item_id.to_s)
  end

  def update_quantity(item_id, quantity)
    @contents[item_id.to_s] = quantity.to_i
    delete(item_id.to_s) if quantity.to_s == "0"
  end

  def total
    items.reduce(0) {|sum, (item,quantity)| sum += item.price*quantity.to_f}
  end

  def create_order_items(order_id)
    items.each {|item,quantity| quantity.to_i.times {OrderItem.create(item_id:item.id, order_id:order_id)}}
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index

  end


  def create
    item = Item.find(params[:item_id])
    @ticket.add_item(item.id)
    session[:ticket] = @ticket.contents
    redirect_to category_name_path(item.category.name)
  end


  def destroy
    @ticket.delete(params[:format])
    redirect_to tickets_path
  end

  def update
    item_id = params[:item_id]
    quantity = params[:quantity]

    @ticket.update_quantity(item_id, quantity)
    redirect_to tickets_path
  end
end

app/views/tickets/index.html.erb
<h3 class="header-font">All Items:</h3>

<div class="jumbotron table-responsive">
  <table class="table table-hover table-bticketed table-condensed table-font">
    <tr> <th class="center-content">Name</th> <th class="center-content">Price</th><th class="center-content">Quantity</th></tr>
      <% @ticket.items.each do |item, quantity| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= number_to_currency(item.price, :unit => "$") %></td>
          <td><%= form_tag update_ticket_path do %>
              <%= text_field_tag "quantity", quantity%>
              <%= hidden_field_tag "item_id", item.id%>
          </td>
          <td><%= button_tag "Update", class: "btn btn-info" %><td>
              <% end %>
          <td><%= button_to "Remove", ticket_path(item.id), method: "delete", class:"btn btn-danger"%> </td>
      <% end  %>
    </tr>
  </table>
  <% if logged_in? %>
    <%= button_to "Submit Ticket", create_order_path(current_user.id), method: "post", class:"btn btn-success" %>
  <% else %>
    <p><%= button_to "Login", login_path, class:"btn btn-success", id:"ticket_login" %> or <%= button_to "Create Account", login_path, class:"btn btn-success" %> to Submit Ticket</p>
  <% end %>
</div>